#!/usr/bin/env bash
set -e

# Check dependencies
if ! command -v docker &>/dev/null; then
  echo "Error: 'docker' is not installed or not in PATH."
  echo "Install Docker Desktop from https://docs.docker.com/get-docker/ and try again."
  exit 1
fi

if ! docker compose version &>/dev/null; then
  echo "Error: 'docker compose' (v2 plugin) is not available."
  echo "Update Docker Desktop or install the Compose plugin: https://docs.docker.com/compose/install/"
  exit 1
fi

# Idempotency guard
if [ -f ".env" ]; then
  echo "'.env' already exists. Remove it first to re-run setup."
  exit 1
fi

echo "Generating secrets..."
JWT_SECRET=$(openssl rand -hex 32)
INTERNAL_API_KEY=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -hex 32)
S3_ACCESS_KEY=$(openssl rand -hex 32)
S3_SECRET_KEY=$(openssl rand -hex 32)

echo ""
read -r -p "Domain (e.g. chat.example.com) [default: :80 for plain HTTP]: " DOMAIN
DOMAIN="${DOMAIN:-:80}"

echo ""
read -r -p "Attachment storage backend (s3/local) [s3]: " ATTACHMENTS_STORAGE_PROVIDER
ATTACHMENTS_STORAGE_PROVIDER="${ATTACHMENTS_STORAGE_PROVIDER:-s3}"
if [ "${ATTACHMENTS_STORAGE_PROVIDER}" != "s3" ] && [ "${ATTACHMENTS_STORAGE_PROVIDER}" != "local" ]; then
  echo "Invalid attachment storage backend: ${ATTACHMENTS_STORAGE_PROVIDER}. Use 's3' or 'local'."
  exit 1
fi

if [ "$DOMAIN" = ":80" ]; then
  ALLOWED_ORIGINS="http://localhost"
  ATTACHMENTS_PUBLIC_BASE_URL="http://localhost:8080/api/v1"
else
  ALLOWED_ORIGINS="https://${DOMAIN}"
  ATTACHMENTS_PUBLIC_BASE_URL="https://${DOMAIN}/api/v1"
fi

echo ""
echo "SMTP settings (optional — leave blank to print OTPs to console)"
echo "Recommended: SendGrid (https://sendgrid.com) — 100 emails/day free"
echo "  SMTP host: smtp.sendgrid.net"
echo "  SMTP user: apikey"
echo "  SMTP pass: <your SendGrid API key>"
echo ""
read -r -p "SMTP host: " SMTP_HOST
read -r -p "SMTP port [587]: " SMTP_PORT
SMTP_PORT="${SMTP_PORT:-587}"
read -r -p "SMTP user: " SMTP_USER
read -r -p "SMTP password: " SMTP_PASS
read -r -p "From address [noreply@${DOMAIN}]: " SMTP_FROM
SMTP_FROM="${SMTP_FROM:-noreply@${DOMAIN}}"

echo ""
echo "Writing .env..."

cat > .env <<EOF
# Auto-generated by setup.sh — do not edit manually
# To regenerate: remove this file and re-run setup.sh

# === Secrets (auto-generated) ===
JWT_SECRET='${JWT_SECRET}'
INTERNAL_API_KEY='${INTERNAL_API_KEY}'
DB_PASSWORD='${DB_PASSWORD}'
S3_ACCESS_KEY='${S3_ACCESS_KEY}'
S3_SECRET_KEY='${S3_SECRET_KEY}'

# === Deployment ===
DOMAIN=${DOMAIN}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
ATTACHMENTS_STORAGE_PROVIDER=${ATTACHMENTS_STORAGE_PROVIDER}
ATTACHMENTS_PUBLIC_BASE_URL=${ATTACHMENTS_PUBLIC_BASE_URL}

# === SMTP (optional) ===
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_FROM=${SMTP_FROM}
EOF

echo ".env written."
echo ""
echo "Starting services..."
docker compose -f docker-compose.prod.yml up -d --build

echo ""
if [ "$DOMAIN" = ":80" ]; then
  echo "Done! Visit http://localhost:8080 to open Tone Chat."
else
  echo "Done! Visit https://${DOMAIN} to open Tone Chat."
fi
