---
services:
  messaging-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
