---
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5001:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./src/sql/seed.sql:/tmp/seed.sql:rw
    command: sh -c "psql -p 5432 postgres < /tmp/seed.sql"
    env_file:
      - .env